#访问端口
server:
  port: 8181
  servlet:
    context-path: /fileTool

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      
logging:
  level:
    org:
      springframework:
        web: DEBUG
      apache:
        tomcat: DEBUG


